/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
	import flash.display.Sprite;
	
	import tests.TestStartBuzzCoffee;
	import tests.TestDuckSimulator;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		private var tests_TestDuckSimulator_obj:tests.TestDuckSimulator;
		
		private var tests_TestStartBuzzCoffee_obj:tests.TestStartBuzzCoffee;
	}
}